export LANG=en_US.utf-8
export EDITOR="emacsclient -nw"
export VISUAL="emacsclient -nc"
# export MANPAGER="/usr/bin/bash -c 'col -bx | /usr/bin/bat -l man -p'"
export BROWSER="brave-nightly"
export ALTERNATE_EDITOR="emacsclient"
export SUDO_EDITOR="emc"
export XCURSOR_SIZE=24
export BAT_THEME=OneHalfDark
export XCURSOR_SIZE=24
export ALTERNATE_EDITOR="emacsclient"
export BAT_THEME=OneHalfDark
export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:/usr/local/share":$XDG_DATA_DIRS
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
# export GNUPG_HOME="$XDG_DATA_HOME"/gnupg
export JUPYTER_CONFIG_DIR=$HOME/.config/jupyter 
export GSETTINGS_SCHEMA_DIR="/usr/share/glib-2.0/schemas" 
export GTK_FILE_CHOOSER_BACKEND="file:///$HOME/.local/share/applications/ranger-file-picker.desktop"
export MOZ_ENABLE_WAYLAND=1
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export SQLITE_HISTORY="$XDG_CACHE_HOME"/sqlite_history
