name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository using git
        run: |
          pacman -Sy git grub sudo archiso --noconfirm
          git clone --recurse-submodules https://github.com/StratOS-Linux/hyprland-iso

      - name: Set up environment and build ISO
        id: build_iso
        run: |
          cd hyprland-iso
          sudo bash ./build.sh
          export BUILD_DATE=$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
          echo "::set-output name=date::${BUILD_DATE}" 

      - name: Create GitHub Release
        id: create_release
        if: steps.build_iso.outcome == 'success'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.BUILD_DATE }}
          release_name: v${{ env.BUILD_DATE }}
          body: |
            Automated release powered by GitHub Actions.

      - name: Upload ISO as Release Asset
        id: upload_asset
        if: steps.build_iso.outcome == 'success'
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hyprland-iso/output/StratOS-${{ env.BUILD_DATE }}-x86_64.iso
          asset_name: StratOS-${{ env.BUILD_DATE }}-x86_64.iso
          asset_content_type: application/octet-stream
